### PR TITLE
changed index and main js files

### PR DESCRIPTION
**Pull request by xam1dullo**

### CODE REVIEW

**Comment by takeda05** [comment]
nimadur

**Comment by Xorazm92** [comment]
Bugungi dars bo'yicha must havelar

**Comment by abdulaz1z31** [comment]
nimalardur yozish kerak eakan yozdim

**Review by abdulaz1z31 — COMMENTED** [review]
reviewed

**Review by Xorazm92 — COMMENTED** [review]
viewed

**Review by takeda05 — COMMENTED** [review]
rewieved

**Pull request merged**
